mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: /mapper/*/*.xml
  type-aliases-package: com.wdjk.webdemo624.entity
#  global-config:
#    db-column-underline: true
#    field-strategy: 0
#    id-type: 0
#    refresh-mapper: true

server:
  port: 8081
  servlet:
    context-path: /wdjk
spring:
  application:
    name: wdjk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/wdjk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: zhuhua
