mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: /mapper/*/*.xml
  type-aliases-package: com.wdjk.webdemo624.entity
  global-config:
    db-config:
      #主键类型 数据库id自增
      id-type: auto
      table-underline: true

#  VJJCBSDRQOOTOIEW


server:
  port: 8081
  servlet:
    context-path: /wdjk
spring:
  application:
    name: wdjk
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/wdjk?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: zhuhua
  mail:
    host: smtp.163.com
    port: 465
    username: leafzhuhua@163.com
    password: VJJCBSDRQOOTOIEW
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  redis:
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-wait: 8
        max-idle: -1
        min-idle: 0
      shutdown-timeout: 5000

logging:
  level:
    com.wdjk.webdemo624: debug
#  日志保存路径
#  file:
#    name: ./log/wdjk.log

#wdjk
wdjk:
  path:
    domain: http://localhost:8081


## Redis数据库索引（默认为0）
#  spring.redis.database=0
#  # Redis服务器地址
#  spring.redis.host=127.0.0.1
#  # Redis服务器连接端口
#  spring.redis.port=6379
#  # Redis服务器连接密码（默认为空）
#  spring.redis.password=
#  # 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-idle=8
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.jedis.pool.max-wait=-1
#  # 连接池中的最小空闲连接
#  spring.redis.jedis.pool.min-idle=0
#  # 连接超时时间（毫秒）
#  spring.redis.jedis.timeout=5000
