-- MySQL Script generated by MySQL Workbench
-- Wed Apr 14 20:01:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wdjk
-- -----------------------------------------------------
-- 无敌女高中生匿名留言板
-- 
DROP SCHEMA IF EXISTS `wdjk` ;

-- -----------------------------------------------------
-- Schema wdjk
--
-- 无敌女高中生匿名留言板
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wdjk` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;

USE `wdjk` ;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_ipaddress`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_ipaddress` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_ipaddress` (
  `fi_id` INT NOT NULL AUTO_INCREMENT COMMENT '论坛IP ID',
  `fi_ipv4` VARCHAR(16) NULL DEFAULT NULL COMMENT 'ipv4地址',
  `fi_ipv6` VARCHAR(128) NULL DEFAULT NULL COMMENT 'ipv6地址\n',
  PRIMARY KEY (`fi_id`))
ENGINE = InnoDB
COMMENT = 'ip表，存储ip地址';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic` (
  `ft_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题id',
  `fu_id` INT NOT NULL COMMENT '发表人 id （对应 forum_user）',
  `ftcg_id` INT NOT NULL COMMENT '话题分类id(对应forum_topic_category)',
  `ft_title` VARCHAR(50) NOT NULL COMMENT '话题标题',
  `ft_last_replytime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后回复时间(默认为当前时间，等同与发布时间)',
  `ft_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '话题创建时间（默认当前时间）',
  `ft_last_replyuserid` INT NULL DEFAULT NULL COMMENT '话题最后回复用户id',
  PRIMARY KEY (`ft_id`),
  CONSTRAINT `FT_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`forum_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FT_L_FU_ID`
    FOREIGN KEY (`ft_last_replyuserid`)
    REFERENCES `wdjk`.`forum_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FT_FTCG_ID`
    FOREIGN KEY (`ftcg_id`)
    REFERENCES `wdjk`.`forum_topic_category` (`ftcg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '话题表，保存话题基本信息';

SHOW WARNINGS;
CREATE INDEX `FT_FU_ID` ON `wdjk`.`forum_topic` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FT_L_FU_ID` ON `wdjk`.`forum_topic` (`ft_last_replyuserid` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FT_FTCG_ID` ON `wdjk`.`forum_topic` (`ftcg_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_action` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_action` (
  `fta_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题行为 id',
  `ft_id` INT NOT NULL COMMENT '话题 id',
  `fta_reply_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有话题用户 id 数组（JSON int）',
  `fta_collect_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有收藏话题用户 id 数组（JSON int）',
  `fta_attention_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有关注话题用户 id 数组（JSON int）',
  `fta_like_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有喜欢话题用户 id 数组（JSON int）',
  PRIMARY KEY (`fta_id`),
  CONSTRAINT `FTA_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '话题操作表，保存用户和话题间的相关操作';

SHOW WARNINGS;
CREATE UNIQUE INDEX `ft_id` ON `wdjk`.`forum_topic_action` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_category` (
  `ftcg_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题分类id',
  `ftcg_is_anonymous` INT NOT NULL DEFAULT '0' COMMENT '话题类型(0-普通类型，1-匿名类型)',
  PRIMARY KEY (`ftcg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '话题分类表，0为普通话题，1为匿名话题';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_content` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_content` (
  `ftc_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题内容 id',
  `ft_id` INT NOT NULL COMMENT '对应话题 id （对应 forum_topic）',
  `fi_id` INT NOT NULL COMMENT '论坛IP ID',
  `ftc_content` LONGTEXT NOT NULL COMMENT '话题内容（longtext 类型，最大长度4294967295个字元 (2^32-1)）',
  `ftc_read` INT NULL DEFAULT '0' COMMENT '话题阅读数',
  `ftc_like` INT NULL DEFAULT '0' COMMENT '喜欢话题人数',
  `ftc_picture` VARCHAR(100) NULL DEFAULT NULL COMMENT '话题内容图片',
  PRIMARY KEY (`ftc_id`),
  CONSTRAINT `FTC_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FTC_FI_ID`
    FOREIGN KEY (`fi_id`)
    REFERENCES `wdjk`.`forum_ipaddress` (`fi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '话题内容表，保存论坛内容相关信息';

SHOW WARNINGS;
CREATE UNIQUE INDEX `FTC` ON `wdjk`.`forum_topic_content` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FTC_FI_ID` ON `wdjk`.`forum_topic_content` (`fi_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_reply` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_reply` (
  `ftr_id` INT NOT NULL COMMENT '话题回复 id',
  `fu_id` INT NULL DEFAULT NULL COMMENT '回复人 id',
  `ft_id` INT NULL DEFAULT NULL COMMENT '对应话题 id',
  `fi_id` INT NOT NULL COMMENT '论坛IP ID',
  `ftr_content` VARCHAR(150) NOT NULL COMMENT '话题内容',
  `ftr_agree` INT NULL DEFAULT '0' COMMENT '回复点赞数',
  `ftr_oppose` INT NULL DEFAULT '0' COMMENT '回复反对数',
  `ftr_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复创建时间',
  PRIMARY KEY (`ftr_id`),
  CONSTRAINT `FTR_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`forum_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FTR_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FTR_FI_ID`
    FOREIGN KEY (`fi_id`)
    REFERENCES `wdjk`.`forum_ipaddress` (`fi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2001
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '话题内容回复表，保存回复内容';

SHOW WARNINGS;
CREATE INDEX `FTR_FU_ID` ON `wdjk`.`forum_topic_reply` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FTR_FT_ID` ON `wdjk`.`forum_topic_reply` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FTR_FI_ID` ON `wdjk`.`forum_topic_reply` (`fi_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_user` (
  `fu_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id\n',
  `fi_id` INT NOT NULL COMMENT '论坛IP ID',
  `fu_name` VARCHAR(15) NULL DEFAULT NULL COMMENT '用户名称 ',
  `fu_password` VARCHAR(200) NOT NULL COMMENT '用户密码',
  `fu_email` VARCHAR(255) NOT NULL COMMENT '用户邮箱地址\n',
  `fu_birthday` VARCHAR(20) NULL DEFAULT NULL COMMENT '用户生日',
  `fu_avator` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户头像地址',
  `fu_description` VARCHAR(255) NULL DEFAULT NULL COMMENT '用户介绍\n',
  `fu_theme` INT NOT NULL DEFAULT '0' COMMENT '用户主题，默认0号主题',
  `fu_rank` INT NOT NULL DEFAULT '0' COMMENT '用户级别(0-普通用户，1-管理员)',
  `fu_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建时间',
  PRIMARY KEY (`fu_id`),
  CONSTRAINT `FU_FI_ID`
    FOREIGN KEY (`fi_id`)
    REFERENCES `wdjk`.`forum_ipaddress` (`fi_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户表，保存用户相关信息';

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_name_UNIQUE` ON `wdjk`.`forum_user` (`fu_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_email_UNIQUE` ON `wdjk`.`forum_user` (`fu_email` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FU_FI_ID` ON `wdjk`.`forum_user` (`fi_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_user_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_user_action` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_user_action` (
  `fua_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户操作 id',
  `fu_id` INT NOT NULL COMMENT '用户 id',
  `fua_like_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户喜欢所有话题 id 数组（JSON int）',
  `fua_collect_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户收藏话题 id 数组（JSON int）',
  `fua_attention_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户关注话题 id 数组（JSON int）',
  `fua_following_fu_id_array` JSON NULL DEFAULT NULL COMMENT '[主动]用户主动关注的用户 id 数组（JSON int）',
  `fua_followed_fu_id_array` JSON NULL DEFAULT NULL COMMENT '[被动]关注该用户的用户 id 数组（JSON int）',
  PRIMARY KEY (`fua_id`),
  CONSTRAINT `FUA_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`forum_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '用户操作表，用户相关操作';

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_id` ON `wdjk`.`forum_user_action` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_user_dynamic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_user_dynamic` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_user_dynamic` (
  `fud_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户动态 id',
  `fu_id` INT NOT NULL COMMENT '用户 id',
  `fud_public_info_array` JSON NULL DEFAULT NULL COMMENT '用户动态信息,用户发布的所有消息（JSON: {{\"发布时间\", \"消息\", \"可见性限制\"},{ ... }}）',
  PRIMARY KEY (`fud_id`),
  CONSTRAINT `FUD_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`forum_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '用户动态表，保存用户动态信息';

SHOW WARNINGS;
CREATE INDEX `FUD_FU_ID` ON `wdjk`.`forum_user_dynamic` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
