-- MySQL Script generated by MySQL Workbench
-- Mon Apr 12 11:42:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wdjk
-- -----------------------------------------------------
-- 无敌女高中生匿名留言板
-- 
DROP SCHEMA IF EXISTS `wdjk` ;

-- -----------------------------------------------------
-- Schema wdjk
--
-- 无敌女高中生匿名留言板
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wdjk` DEFAULT CHARACTER SET utf8mb4 ;
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema neubbs
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema forum
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema nkbbs
-- -----------------------------------------------------
SHOW WARNINGS;
USE `wdjk` ;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_message`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_message` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_message` (
  `fm_id` INT NOT NULL AUTO_INCREMENT COMMENT '消息 id',
  `fm_source` VARCHAR(20) NOT NULL COMMENT '消息来源',
  `fm_sender_id` INT NOT NULL COMMENT '发送人 id',
  `fm_send_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间（默认为创建时间）',
  `fm_content` VARCHAR(500) NOT NULL COMMENT '消息内容',
  `fm_receiver_id` INT NOT NULL COMMENT '接收人 id',
  `fm_receive_time` DATETIME NULL DEFAULT NULL COMMENT '接收时间（默认空）',
  PRIMARY KEY (`fm_id`),
  CONSTRAINT `FM_R_FU_ID`
    FOREIGN KEY (`fm_receiver_id`)
    REFERENCES `neubbs`.`forum_user` (`fu_id`),
  CONSTRAINT `FM_S_FU_ID`
    FOREIGN KEY (`fm_sender_id`)
    REFERENCES `neubbs`.`forum_user` (`fu_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE INDEX `FM_S_FU_ID` ON `wdjk`.`forum_message` (`fm_sender_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FM_R_FU_ID` ON `wdjk`.`forum_message` (`fm_receiver_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic` (
  `ft_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题id',
  `fu_id` INT NOT NULL COMMENT '发表人 id （对应 forum_user）',
  `ftcg_id` INT NOT NULL COMMENT '话题分类id(对应forum_topic_category)',
  `ft_title` VARCHAR(50) NOT NULL COMMENT '话题标题',
  `ft_last_replytime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最后回复时间(默认为当前时间，等同与发布时间)',
  `ft_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '话题创建时间（默认当前时间）',
  `ft_last_replyuserid` INT NULL DEFAULT NULL COMMENT '话题最后回复用户id',
  PRIMARY KEY (`ft_id`),
  CONSTRAINT `fk_forum_topic_fourm_user`
    FOREIGN KEY (`fu_id`)
    REFERENCES `forum`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_fourm_user1`
    FOREIGN KEY (`ft_last_replyuserid`)
    REFERENCES `forum`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_fourm_user2`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_fourm_user3`
    FOREIGN KEY (`ft_last_replyuserid`)
    REFERENCES `wdjk`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_forum_topic_category1`
    FOREIGN KEY (`ftcg_id`)
    REFERENCES `wdjk`.`forum_topic_category` (`ftcg_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_forum_topic_fourm_user_idx` ON `wdjk`.`forum_topic` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_forum_topic_fourm_user1_idx` ON `wdjk`.`forum_topic` (`ft_last_replyuserid` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `fk_forum_topic_forum_topic_category1_idx` ON `wdjk`.`forum_topic` (`ftcg_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_action` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_action` (
  `fta_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题行为 id',
  `ft_id` INT NOT NULL COMMENT '话题 id',
  `fta_reply_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有话题用户 id 数组（JSON int）',
  `fta_collect_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有收藏话题用户 id 数组（JSON int）',
  `fta_attention_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有关注话题用户 id 数组（JSON int）',
  `fta_like_fu_id_array` JSON NULL DEFAULT NULL COMMENT '所有喜欢话题用户 id 数组（JSON int）',
  PRIMARY KEY (`fta_id`),
  CONSTRAINT `FTA_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `neubbs`.`forum_topic` (`ft_id`),
  CONSTRAINT `fk_forum_topic_action_forum_topic1`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ft_id` ON `wdjk`.`forum_topic_action` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_category` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_category` (
  `ftcg_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题分类id',
  `ftcg_is_anonymous` INT NOT NULL DEFAULT '0' COMMENT '话题类型(0-普通类型，1-匿名类型)',
  PRIMARY KEY (`ftcg_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_content`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_content` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_content` (
  `ftc_id` INT NOT NULL AUTO_INCREMENT COMMENT '话题内容 id',
  `ft_id` INT NOT NULL COMMENT '对应话题 id （对应 forum_topic）',
  `ftc_content` LONGTEXT NOT NULL COMMENT '话题内容（longtext 类型，最大长度4294967295个字元 (2^32-1)）',
  `ftc_read` INT NULL DEFAULT '0' COMMENT '话题阅读数',
  `ftc_like` INT NULL DEFAULT '0' COMMENT '喜欢话题人数',
  `ftc_picture` VARCHAR(100) NULL DEFAULT NULL COMMENT '话题内容图片',
  PRIMARY KEY (`ftc_id`),
  CONSTRAINT `FTC_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `neubbs`.`forum_topic` (`ft_id`),
  CONSTRAINT `fk_forum_topic_content_forum_topic1`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `ft_id` ON `wdjk`.`forum_topic_content` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_topic_reply`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_topic_reply` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_topic_reply` (
  `ftr_id` INT NOT NULL COMMENT '话题回复 id',
  `fu_id` INT NULL DEFAULT NULL COMMENT '回复人 id',
  `fu_last_ipv4` VARCHAR(16) NULL DEFAULT NULL COMMENT '用户最后登录ipv4地址',
  `ft_last_replyipv6` VARCHAR(128) NULL DEFAULT NULL,
  `ft_id` INT NULL DEFAULT NULL COMMENT '对应话题 id',
  `ftr_content` VARCHAR(150) NOT NULL COMMENT '话题内容',
  `ftr_agree` INT NULL DEFAULT '0' COMMENT '回复点赞数',
  `ftr_oppose` INT NULL DEFAULT '0' COMMENT '回复反对数',
  `ftr_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '回复创建时间',
  PRIMARY KEY (`ftr_id`),
  CONSTRAINT `FTR_FT_ID`
    FOREIGN KEY (`ft_id`)
    REFERENCES `neubbs`.`forum_topic` (`ft_id`),
  CONSTRAINT `FTR_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `neubbs`.`forum_user` (`fu_id`),
  CONSTRAINT `fk_forum_topic_reply_fourm_user1`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_forum_topic_reply_forum_topic1`
    FOREIGN KEY (`ft_id`)
    REFERENCES `wdjk`.`forum_topic` (`ft_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2001
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE INDEX `FTR_FU_ID` ON `wdjk`.`forum_topic_reply` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;
CREATE INDEX `FTR_FT_ID` ON `wdjk`.`forum_topic_reply` (`ft_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_user_action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_user_action` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_user_action` (
  `fua_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户操作 id',
  `fu_id` INT NOT NULL COMMENT '用户 id',
  `fua_like_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户喜欢所有话题 id 数组（JSON int）',
  `fua_collect_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户收藏话题 id 数组（JSON int）',
  `fua_attention_ft_id_array` JSON NULL DEFAULT NULL COMMENT '用户关注话题 id 数组（JSON int）',
  `fua_following_fu_id_array` JSON NULL DEFAULT NULL COMMENT '[主动]用户主动关注的用户 id 数组（JSON int）',
  `fua_followed_fu_id_array` JSON NULL DEFAULT NULL COMMENT '[被动]关注该用户的用户 id 数组（JSON int）',
  PRIMARY KEY (`fua_id`),
  CONSTRAINT `FUA_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `neubbs`.`forum_user` (`fu_id`),
  CONSTRAINT `fk_forum_user_action_fourm_user1`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_id` ON `wdjk`.`forum_user_action` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`forum_user_dynamic`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`forum_user_dynamic` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`forum_user_dynamic` (
  `fud_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户动态 id',
  `fu_id` INT NOT NULL COMMENT '用户 id',
  `fud_public_info_array` JSON NULL DEFAULT NULL COMMENT '用户动态信息,用户发布的所有消息（JSON: {{\"发布时间\", \"消息\", \"可见性限制\"},{ ... }}）',
  PRIMARY KEY (`fud_id`),
  CONSTRAINT `FUD_FU_ID`
    FOREIGN KEY (`fu_id`)
    REFERENCES `neubbs`.`forum_user` (`fu_id`),
  CONSTRAINT `fk_forum_user_dynamic_fourm_user1`
    FOREIGN KEY (`fu_id`)
    REFERENCES `wdjk`.`fourm_user` (`fu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;

SHOW WARNINGS;
CREATE INDEX `FUD_FU_ID` ON `wdjk`.`forum_user_dynamic` (`fu_id` ASC) VISIBLE;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `wdjk`.`fourm_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wdjk`.`fourm_user` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `wdjk`.`fourm_user` (
  `fu_id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id\n',
  `fu_name` VARCHAR(15) NULL DEFAULT NULL COMMENT '用户名称 ',
  `fu_password` VARCHAR(200) NOT NULL COMMENT '用户密码',
  `fu_email` VARCHAR(255) NOT NULL COMMENT '用户邮箱地址\n',
  `fu_birthday` VARCHAR(20) NULL DEFAULT NULL COMMENT '用户生日',
  `fu_avator` VARCHAR(100) NULL DEFAULT NULL COMMENT '用户头像地址',
  `fu_description` VARCHAR(255) NULL DEFAULT NULL COMMENT '用户介绍\n',
  `fu_theme` INT NOT NULL DEFAULT '0' COMMENT '用户主题，默认0号主题',
  `fu_rank` INT NOT NULL DEFAULT '0' COMMENT '用户级别(0-普通用户，1-管理员)',
  `fu_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '用户创建时间',
  `fu_last_ipv4` VARCHAR(16) NULL DEFAULT NULL COMMENT '用户最后登录ipv4地址',
  `fu_last_ipv6` VARCHAR(128) NULL DEFAULT NULL COMMENT '用户登录最后ipv6地址\n',
  PRIMARY KEY (`fu_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_name_UNIQUE` ON `wdjk`.`fourm_user` (`fu_name` ASC) VISIBLE;

SHOW WARNINGS;
CREATE UNIQUE INDEX `fu_email_UNIQUE` ON `wdjk`.`fourm_user` (`fu_email` ASC) VISIBLE;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
